In [ ]:
#구글 드라이브 마운트하기
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/data/data.db")
cur = conn.cursor()

def select_func(qry):
  cur.execute(SQL_TEXT)
  cols = [column[0] for column in cur.description]
  result = pd.DataFrame.from_records(data=cur.fetchall(), columns=cols)
  return result

In [ ]:
SQL_TEXT = """

SELECT * FROM sqlite_master WHERE type='table'
 
"""

result = select_func(SQL_TEXT)
result

,type,name,tbl_name,rootpage,sql
0,table,gmv_trend,gmv_trend,4,"CREATE TABLE ""gmv_trend"" (\n\t""category""\tTEXT..."
1,table,user_info,user_info,2,"CREATE TABLE ""user_info"" (\n\t""userid""\tINTEGE..."
2,table,online_order,online_order,23,"CREATE TABLE ""online_order"" (\n\t""dt""\tINTEGER..."
3,table,item,item,98,"CREATE TABLE ""item"" (\n\t""id""\tINTEGER,\n\t""it..."
4,table,category,category,99,"CREATE TABLE ""category"" (\n\t""id""\tINTEGER,\n\..."

In [ ]:
SQL_TEXT = """

select * 
  from gmv_trend
 limit 10
 
"""

result = select_func(SQL_TEXT)
result

      category  yyyy  mm platform_type      gmv
0   컴퓨터 및 주변기기  2017   1        mobile  133,993
1   가전·전자·통신기기  2017   1        mobile  294,626
2           서적  2017   1        mobile   47,379
3        사무·문구  2017   1        mobile   15,959
4           의복  2017   1        mobile  467,093
5           신발  2017   1        mobile   61,269
6           가방  2017   1        mobile   99,665
7  패션용품 및 액세서리  2017   1        mobile   86,770
8     스포츠·레저용품  2017   1        mobile   96,891
9          화장품  2017   1        mobile  380,746